### ISSUE TITLE
Create Items Model 

### ISSUE THREAD

**Issue by nirzaf** [quadrate-tech/QTS-SimpleBilling#5]
Since this class has relation with following classes you to create all of them
Shelf
Category
Unit
Cost
Selling Price

![image](https://user-images.githubusercontent.com/18024930/107197453-e8f48e00-6a19-11eb-88bd-22844e3aa606.png)

**Comment by sakeeljawfer** [comment]
#5

**Comment by sakeeljawfer** [comment]
Create Items Model #5
